version: '2'

services:
  angular:
    build: angular-client
    environment:
      - VIRTUAL_HOST=adverse.andrew-chiu.com
      - LETSENCRYPT_HOST=adverse.andrew-chiu.com
      - LETSENCRYPT_HOST=andrewchiu04@gmail.com
    network_mode: "bridge"
    ports:
      - "4200"

  express:
    build: express-server
    ports:
      - "3000"
    environment:
      - VIRTUAL_HOST=adverse.api.andrew-chiu.com
      - LETSENCRYPT_HOST=adverse.api.andrew-chiu.com
      - LETSENCRYPT_HOST=andrewchiu04@gmail.com
    network_mode: "bridge"
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017"

  mongo-seed:
    build: ./mongo-seed
    links:
      - database
